apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: redmine
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: "mysql"
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql    
    spec:
      containers:
      - image: mysql:5.7
        imagePullPolicy: Always
        name: mysql
        ports:
        - containerPort: 3306
          name: mysql 
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: super-secret
              key: mysqlpd
        volumeMounts:
        - mountPath: "/var/lib/mysql"
          name: mypd
      volumes:
      - name: mypd
        persistentVolumeClaim:
           claimName: pvc-redmine
