apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2024-09-30T06:33:50Z"
  generation: 1
  labels:
    app: web
  name: app
  namespace: default
  resourceVersion: "104044"
  uid: dfe276ad-53b9-427e-bff8-a018633c3b81
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: web
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: web
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginx
      