apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redmine-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 3Gi
  storageClassName: local-redmine
~                                     
