apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-09-24T05:35:25Z"
  labels:
    run: nginx
  name: nginx
  namespace: default
  resourceVersion: "65671"
  uid: d1be37d9-9859-419d-8952-865e0a3a98ce
spec:
  nodeName: minikube-m02
  containers: 
  - image: nginx:1.14.2
    imagePullPolicy: Always
    name: nginx
    ports:
       - containerPort: 80
    resources:
      requests:
        cpu: 700m
        memory: 700Mi
      limits:
        cpu: 700m
        memory: 1024Mi
