apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-09-24T05:35:25Z"
  labels:
    run: nginx
  name: nginx
  namespace: default
  resourceVersion: "65671"
  uid: d1be37d9-9859-419d-8952-865e0a3a98ce
spec:
  containers:
  - image: nginx
    imagePullPolicy: Always
    name: nginx
    ports:
      - containerPort: 80
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/os
            operator: In
            values:
            - linux
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: label-1
            operator: In
            values:
            - key-1
      - weight: 50
        preference:
          matchExpressions:
          - key: label-2
            operator: In
            values:
            - key-2
