apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
spec:
  serviceName: mongo
  replicas: 3
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo:4.0.8
        args: ["--dbpath", "/data/db"]
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "admin"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "password"
        command:
        - mongod
        - "--bind_ip_all"
        - "--replSet"                # Correct flag to set replica set
        - rs0                        # Name of the replica set
        - "--wiredTigerCacheSizeGB"
        - "2"
        - "--wiredTigerJournalCompressor"
        - "zlib"
        - "--enableFreeMonitoring"
        - "on"
        ports:
        - name: mongo-port
          containerPort: 27017
        volumeMounts:
        - name: mongo-volume
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongo-volume
    spec:
      storageClassName: "local-mongo"
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
